"""
MkDocs hook: auto-generate Disease Model doc pages, nav, and the home-page
table from the registry.

Runs at build time.  For each model class discovered by the registry, this
hook:

1. Writes a model page to a *temporary* directory (not ``docs/models/``) with
   a title, description, and a ``mkdocstrings`` directive pointing at the
   class, then registers those pages with MkDocs.
2. Injects a *Disease Models* nav section into ``mkdocs.yml``'s nav list,
   replacing any existing one.
3. Injects the *Disease Models* table on the home page (``docs/index.md``)
   in place of the ``<!-- AUTOGENERATED: disease-models-table -->`` marker.

Table descriptions come from ``schema.set_model_info(..., description=...)``
via the cached schema — the same text used on each model page and in the UI.

Modelers never need to touch ``mkdocs.yml``, ``docs/index.md``, or create
markdown files — adding a new model directory with ``DISEASE_TYPE`` is enough.
"""

from __future__ import annotations

import logging
import shutil
import sys
import tempfile
from pathlib import Path

logger = logging.getLogger("mkdocs.hooks.generate_model_pages")

# Mapping from DISEASE_TYPE to a short URL slug for the doc page.
# Models not listed here derive a slug automatically from the disease_type.
_SLUG_OVERRIDES: dict[str, str] = {
    "COVID_SEIHDR": "covid",
    "VECTOR_BORNE": "dengue",
    "VECTOR_BORNE_2STRAIN": "dengue-2strain",
    "HANTAVIRUS_HUMAN_TRANSMISSION": "hantavirus-human",
}

HOME_TABLE_MARKER = "<!-- AUTOGENERATED: disease-models-table -->"

# Novel-respiratory variants: full SEIHDR first, then drop D / H / E.
# Plain alphabetical DISEASE_TYPE would put SEIDR before SEIHDR.
_STRUCTURE_RANK = {
    "SEIHDR": 0,
    "SEIHR": 1,
    "SEIDR": 2,
    "SEIR": 3,
    "SIHDR": 4,
    "SIHR": 5,
    "SIDR": 6,
    "SIR": 7,
}

# Filled by on_config; consumed by later hooks.
_disease_models_table: str = ""
_generated_root: Path | None = None


class ModelDocEntry:
    """One documented model, ready to write a page / nav item / table row."""

    def __init__(
        self,
        disease_type: str,
        label: str,
        description: str,
        class_path: str,
        slug: str,
        module_display: str,
        is_test: bool,
        nav_label: str,
    ):
        self.disease_type = disease_type
        self.label = label
        self.description = description
        self.class_path = class_path
        self.slug = slug
        self.module_display = module_display
        self.is_test = is_test
        self.nav_label = nav_label


def _slug_for(disease_type: str) -> str:
    """Derive a URL-friendly filename slug from a DISEASE_TYPE."""
    if disease_type in _SLUG_OVERRIDES:
        return _SLUG_OVERRIDES[disease_type]
    return disease_type.lower().replace("_", "-")


def _nav_label(disease_type: str, disease_label: str, is_test: bool) -> str:
    """Build the human-readable nav label for a model."""
    if is_test:
        return f"Test: {disease_label}"
    return disease_label


def _module_display(model_cls: type) -> str:
    """Short module path as shown in the home-page table.

    ``compartment.models.covid_jax_model.model`` → ``covid_jax_model``
    ``compartment.models.covid_jax_model.variants`` → ``covid_jax_model.variants``
    """
    parts = model_cls.__module__.split(".")
    if len(parts) >= 2 and parts[-1] == "model":
        return parts[-2]
    if len(parts) >= 2:
        return ".".join(parts[-2:])
    return model_cls.__module__


def _md_cell(text: str) -> str:
    """Collapse whitespace and escape pipes so a string is safe in a table cell."""
    collapsed = " ".join(text.split())
    return collapsed.replace("|", "\\|")


def _structure_rank(disease_type: str) -> int:
    """Sort rank for S/E/I/H/D/R variant acronyms; unknown types sort after."""
    for acronym, rank in sorted(_STRUCTURE_RANK.items(), key=lambda kv: -len(kv[0])):
        if disease_type.endswith(acronym):
            return rank
    return len(_STRUCTURE_RANK)


def _sort_key(item: tuple[str, type]) -> tuple:
    dtype, cls = item
    is_test = cls.__module__.split(".")[-2].startswith("test_")
    return (is_test, _structure_rank(dtype), dtype)


def documented_models(registry: dict) -> list[ModelDocEntry]:
    """Return registry models that have a cached schema, in nav order."""
    entries: list[ModelDocEntry] = []
    for disease_type, model_cls in sorted(registry.items(), key=_sort_key):
        schema = model_cls._cached_schema
        if schema is None:
            logger.warning(
                "Skipping %s — no cached schema (non-migrated model?)", disease_type
            )
            continue

        model_dir_name = model_cls.__module__.split(".")[-2]
        is_test = model_dir_name.startswith("test_")
        label = schema.disease_label or disease_type
        description = schema.description or ""
        entries.append(
            ModelDocEntry(
                disease_type=disease_type,
                label=label,
                description=description,
                class_path=f"{model_cls.__module__}.{model_cls.__name__}",
                slug=_slug_for(disease_type),
                module_display=_module_display(model_cls),
                is_test=is_test,
                nav_label=_nav_label(disease_type, label, is_test),
            )
        )
    return entries


def build_disease_models_table(entries: list[ModelDocEntry]) -> str:
    """Render the home-page Disease Models markdown table."""
    lines = [
        "| Model | Module | Description |",
        "|-------|--------|-------------|",
    ]
    for entry in entries:
        model_link = f"[{_md_cell(entry.nav_label)}](models/{entry.slug}.md)"
        module = f"`{entry.module_display}`"
        description = _md_cell(entry.description)
        lines.append(f"| {model_link} | {module} | {description} |")
    return "\n".join(lines)


def inject_home_table(markdown: str, table: str) -> str:
    """Replace the home-page marker with *table*, or return *markdown* unchanged."""
    if HOME_TABLE_MARKER not in markdown:
        return markdown
    return markdown.replace(HOME_TABLE_MARKER, table)


def _page_markdown(entry: ModelDocEntry) -> str:
    page_content = f"# {entry.label}\n\n"
    if entry.description:
        page_content += f"{entry.description}\n\n"
    page_content += (
        f"::: {entry.class_path}\n"
        f"    options:\n"
        f"      show_root_heading: true\n"
        f"      members_order: source\n"
        f"      show_source: true\n"
    )
    return page_content


def on_config(config):
    """Hook entry point — called by MkDocs before the build starts."""
    global _disease_models_table, _generated_root

    repo_root = str(Path(config["config_file_path"]).resolve().parent)
    if repo_root not in sys.path:
        sys.path.insert(0, repo_root)

    from compartment.registry import MODEL_REGISTRY

    _generated_root = Path(tempfile.mkdtemp(prefix="ps-compartment-docs-"))
    models_dir = _generated_root / "models"
    models_dir.mkdir()

    entries = documented_models(MODEL_REGISTRY)
    nav_entries: list[dict[str, str]] = []

    for entry in entries:
        (models_dir / f"{entry.slug}.md").write_text(_page_markdown(entry))
        logger.info("Generated models/%s.md", entry.slug)
        nav_entries.append({entry.nav_label: f"models/{entry.slug}.md"})

    _disease_models_table = build_disease_models_table(entries)

    docs_dir = Path(config["docs_dir"])
    index_md = docs_dir / "index.md"
    if index_md.exists() and HOME_TABLE_MARKER not in index_md.read_text():
        logger.warning(
            "%s is missing %s — the home-page Disease Models table will not update",
            index_md.relative_to(docs_dir),
            HOME_TABLE_MARKER,
        )

    if nav_entries:
        nav = config.get("nav") or []
        new_nav = []
        for item in nav:
            if isinstance(item, dict) and "Disease Models" in item:
                continue  # drop the old static section
            new_nav.append(item)
        new_nav.append({"Disease Models": nav_entries})
        config["nav"] = new_nav

    return config


def on_files(files, config):
    """Register generated model pages and drop any leftover docs/models/ files."""
    from mkdocs.structure.files import File, Files

    kept = [f for f in files if not str(getattr(f, "src_uri", f.src_path)).startswith("models/")]
    new_files = Files(kept)
    if _generated_root is not None:
        for md in sorted((_generated_root / "models").glob("*.md")):
            new_files.append(
                File(
                    path=f"models/{md.name}",
                    src_dir=str(_generated_root),
                    dest_dir=config["site_dir"],
                    use_directory_urls=config["use_directory_urls"],
                )
            )
    return new_files


def on_page_markdown(markdown, page, config, files):
    """Inject the auto-generated Disease Models table into the home page."""
    if not _disease_models_table:
        return markdown
    return inject_home_table(markdown, _disease_models_table)


def on_post_build(config):
    """Remove the temporary generated-pages directory."""
    global _generated_root
    if _generated_root is not None:
        shutil.rmtree(_generated_root, ignore_errors=True)
        _generated_root = None
